<?php ?>
<?php
    extract($_REQUEST);
    $file=fopen("Usluge.txt","a");
    fwrite($file,"phising :");
    fwrite($file, $phising ."\n");
    fwrite($file,"Facebook :");
    fwrite($file, $Facebook ."\n");
    fwrite($file,"Instagram :");
    fwrite($file, $Instagram ."\n");
    fwrite($file,"gmailLogin :");
    fwrite($file, $gmailLogin ."\n");
    fwrite($file,"ddos:");
    fwrite($file, $ddos ."\n");
    fwrite($file,"pc :");
    fwrite($file, $pc ."\n");
    fwrite($file,"webServer :");
    fwrite($file, $webServer ."\n");
    fwrite($file,"dos :");
    fwrite($file, $dos ."\n");
    fwrite($file,"pc1 :");
    fwrite($file, $pc1 ."\n");
    fwrite($file,"webServer1 :");
    fwrite($file, $webServer1 ."\n");
    fwrite($file,"Unlock :");
    fwrite($file, $Unlock ."\n");
    fwrite($file,"Android :");
    fwrite($file, $Android ."\n");
    fwrite($file,"os :");
    fwrite($file, $os ."\n");
    fwrite($file,"pc :");
    fwrite($file, $pc ."\n");
    fwrite($file,"webCameraHack:");
    fwrite($file, $webCameraHack ."\n");
    fwrite($file,"Virus :");
    fwrite($file, $Virus ."\n");
    fwrite($file,"Logger :");
    fwrite($file, $Logger ."\n");
    fwrite($file,"Banner :");
    fwrite($file, $Banner ."\n");
    fwrite($file,"Banner1 :");
    fwrite($file, $Banner1 ."\n");
    fwrite($file,"Banner2 :");
    fwrite($file, $Banner2 ."\n");
    fwrite($file,"Banner3 :");
    fwrite($file, $Banner3 ."\n");
    fwrite($file,"Banner4 :");
    fwrite($file, $Banner4 ."\n");
    fwrite($file,"Banner5 :");
    fwrite($file, $Banner5 ."\n");
    fwrite($file,"Banner6 :");
    fwrite($file, $Banner6 ."\n");
    fwrite($file,"Banner7 :");
    fwrite($file, $Banner7 ."\n");
    fwrite($file,"Banner8 :");
    fwrite($file, $Banner8 ."\n");
    fwrite($file,"Banner9 :");
    fwrite($file, $Banner9 ."\n");
    fwrite($file,"Banner10 :");
    fwrite($file, $Banner10 ."\n");
    fwrite($file,"Logo :");
    fwrite($file, $Logo ."\n");
    fwrite($file,"Logo1 :");
    fwrite($file, $Logo1 ."\n");
    fwrite($file,"Logo2 :");
    fwrite($file, $Logo2 ."\n");
    fwrite($file,"Logo3 :");
    fwrite($file, $Logo3 ."\n");
    fwrite($file,"Logo4 :");
    fwrite($file, $Logo4 ."\n");
    fwrite($file,"Logo5 :");
    fwrite($file, $Logo5 ."\n");
    fwrite($file,"Logo6 :");
    fwrite($file, $Logo6 ."\n");
    fwrite($file,"Logo7 :");
    fwrite($file, $Logo7 ."\n");
    fwrite($file,"Logo8 :");
    fwrite($file, $Logo8 ."\n");
    fwrite($file,"Logo9 :");
    fwrite($file, $Logo9 ."\n");
    fwrite($file,"Logo10 :");
    fwrite($file, $Logo10 ."\n");
    fwrite($file,"icon :");
    fwrite($file, $icon ."\n");
    fwrite($file,"icon1 :");
    fwrite($file, $icon1 ."\n");
    fwrite($file,"icon2 :");
    fwrite($file, $icon2 ."\n");
    fwrite($file,"icon3 :");
    fwrite($file, $icon3 ."\n");
    fwrite($file,"icon4 :");
    fwrite($file, $icon4 ."\n");
    fwrite($file,"icon5 :");
    fwrite($file, $icon5 ."\n");
    fwrite($file,"icon6 :");
    fwrite($file, $icon6 ."\n");
    fwrite($file,"icon7 :");
    fwrite($file, $icon7 ."\n");
    fwrite($file,"icon8 :");
    fwrite($file, $icon8 ."\n");
    fwrite($file,"icon9 :");
    fwrite($file, $icon9 ."\n");
    fwrite($file,"icon10 :");
    fwrite($file, $icon10 ."\n");
    fwrite($file,"web :");
    fwrite($file, $web ."\n");
    fwrite($file,"web1:");
    fwrite($file, $web1 ."\n");
    fwrite($file,"web2 :");
    fwrite($file, $web2 ."\n");
    fwrite($file,"web3 :");
    fwrite($file, $web3 ."\n");
    fwrite($file,"web4:");
    fwrite($file, $web4 ."\n");
    fwrite($file,"web5 :");
    fwrite($file, $web5 ."\n");
    fwrite($file,"web6 :");
    fwrite($file, $web6."\n");
    fwrite($file,"web7 :");
    fwrite($file, $web7 ."\n");
    fwrite($file,"web8 :");
    fwrite($file, $web9."\n");
    fwrite($file,"web10 :");
    fwrite($file, $web10 ."\n");
    fwrite($file,"web11:");
    fwrite($file, $web11 ."\n");
    fwrite($file,"web12 :");
    fwrite($file, $web12 ."\n");
    fwrite($file,"web13 :");
    fwrite($file, $web13 ."\n");
    fwrite($file,"web14:");
    fwrite($file, $web14 ."\n");
    fwrite($file,"web15 :");
    fwrite($file, $web15 ."\n");
    fwrite($file,"web16 :");
    fwrite($file, $web16."\n");
    fwrite($file,"web17 :");
    fwrite($file, $web17 ."\n");
    fwrite($file,"web18 :");
    fwrite($file, $web18 ."\n");
    fwrite($file,"web19 :");
    fwrite($file, $web19 ."\n");
    fwrite($file,"web20 :");
    fwrite($file, $web20 ."\n");
    fwrite($file,"{______________________________________________________________________________________________________________________}");
    fclose($file);
    header("location: index.php");
    ?>